const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const {execFileSync} = require('node:child_process');
const esbuild = require('esbuild');
const pbjs = require('protobufjs-cli/pbjs');

async function main() {
  const root = path.resolve(__dirname, '../..');
  const check = process.argv.includes('--check');
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'certainstats-protobuf-'));
  const schema = 'protocol/browser/v1/telemetry.proto';
  const goFile = 'internal/ws/browserpb/telemetry.pb.go';
  const jsFile = 'web/static/js/browser_protocol.js';
  try {
    if (execFileSync('protoc', ['--version'], {encoding: 'utf8'}).trim() !== 'libprotoc 36.1') {
      throw new Error('Regeneration requires protoc 36.1');
    }
    const plugin = path.join(tmp, 'protoc-gen-go');
    execFileSync('go', ['build', '-o', plugin, 'google.golang.org/protobuf/cmd/protoc-gen-go'], {cwd: root, stdio: 'inherit'});
    execFileSync('protoc', ['-I', root, '--plugin=protoc-gen-go=' + plugin,
      '--go_out=' + tmp, '--go_opt=module=certainstats', schema], {cwd: root, stdio: 'inherit'});
    const generated = await new Promise((resolve, reject) => pbjs.main([
      '-t', 'static-module', '-w', 'commonjs', '--keep-case', '--force-long',
      '--no-create', '--no-encode', '--no-verify', '--no-convert', '--no-delimited',
      '--no-typeurl', '--no-comments', path.join(root, schema)
    ], (err, output) => err ? reject(err) : resolve(output)));
    fs.writeFileSync(path.join(tmp, 'telemetry.cjs'), generated);
    const result = await esbuild.build({
      stdin: {contents: fs.readFileSync(path.join(__dirname, 'browser.cjs'), 'utf8'), resolveDir: tmp, sourcefile: 'browser.cjs'},
      nodePaths: [path.join(__dirname, 'node_modules')],
      bundle: true, format: 'iife', globalName: 'CertainStatsBrowserProtocol',
      platform: 'browser', target: 'es2020', minify: true, write: false,
      // Use long's JavaScript fallback without attempting CSP-blocked Wasm compilation.
      define: {WebAssembly: 'undefined'},
      legalComments: 'inline', banner: {js: '// Generated by tools/browser-protocol/generate.cjs. Do not edit.'}
    });
    const outputs = [[goFile, fs.readFileSync(path.join(tmp, goFile))], [jsFile, result.outputFiles[0].contents]];
    for (const [name, contents] of outputs) {
      const target = path.join(root, name);
      if (check) {
        if (!fs.existsSync(target) || !fs.readFileSync(target).equals(Buffer.from(contents))) throw new Error(name + ' needs regeneration');
      } else fs.writeFileSync(target, contents);
    }
    console.log(check ? 'Generated protocol artifacts are current.' : 'Generated Go and browser protocol artifacts.');
  } finally { fs.rmSync(tmp, {recursive: true, force: true}); }
}
main().catch(err => {console.error(err); process.exitCode = 1;});
