// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: protocol/browser/v1/telemetry.proto

package browserpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// One full pulse per WebSocket binary frame. Map keys are private IDs for
// authenticated owners and public IDs for public dashboard viewers.
type TelemetryEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pulse         *TelemetryPulse        `protobuf:"bytes,1,opt,name=pulse,proto3" json:"pulse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryEnvelope) Reset() {
	*x = TelemetryEnvelope{}
	mi := &file_protocol_browser_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryEnvelope) ProtoMessage() {}

func (x *TelemetryEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_browser_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryEnvelope.ProtoReflect.Descriptor instead.
func (*TelemetryEnvelope) Descriptor() ([]byte, []int) {
	return file_protocol_browser_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryEnvelope) GetPulse() *TelemetryPulse {
	if x != nil {
		return x.Pulse
	}
	return nil
}

type TelemetryPulse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        map[string]*Snapshot   `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryPulse) Reset() {
	*x = TelemetryPulse{}
	mi := &file_protocol_browser_v1_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryPulse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryPulse) ProtoMessage() {}

func (x *TelemetryPulse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_browser_v1_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryPulse.ProtoReflect.Descriptor instead.
func (*TelemetryPulse) Descriptor() ([]byte, []int) {
	return file_protocol_browser_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *TelemetryPulse) GetAgents() map[string]*Snapshot {
	if x != nil {
		return x.Agents
	}
	return nil
}

// Absent wrapper = not provided/allowed. Present empty wrapper = unavailable.
// Explicit scalar presence preserves measured zero and full uint64 precision.
type FloatValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *float64               `protobuf:"fixed64,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FloatValue) Reset() {
	*x = FloatValue{}
	mi := &file_protocol_browser_v1_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloatValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatValue) ProtoMessage() {}

func (x *FloatValue) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_browser_v1_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatValue.ProtoReflect.Descriptor instead.
func (*FloatValue) Descriptor() ([]byte, []int) {
	return file_protocol_browser_v1_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *FloatValue) GetValue() float64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type UintValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *uint64                `protobuf:"varint,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UintValue) Reset() {
	*x = UintValue{}
	mi := &file_protocol_browser_v1_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UintValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UintValue) ProtoMessage() {}

func (x *UintValue) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_browser_v1_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UintValue.ProtoReflect.Descriptor instead.
func (*UintValue) Descriptor() ([]byte, []int) {
	return file_protocol_browser_v1_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *UintValue) GetValue() uint64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type DiskList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Disk                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskList) Reset() {
	*x = DiskList{}
	mi := &file_protocol_browser_v1_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskList) ProtoMessage() {}

func (x *DiskList) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_browser_v1_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskList.ProtoReflect.Descriptor instead.
func (*DiskList) Descriptor() ([]byte, []int) {
	return file_protocol_browser_v1_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *DiskList) GetItems() []*Disk {
	if x != nil {
		return x.Items
	}
	return nil
}

type LoadAverage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float64              `protobuf:"fixed64,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadAverage) Reset() {
	*x = LoadAverage{}
	mi := &file_protocol_browser_v1_telemetry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadAverage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadAverage) ProtoMessage() {}

func (x *LoadAverage) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_browser_v1_telemetry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadAverage.ProtoReflect.Descriptor instead.
func (*LoadAverage) Descriptor() ([]byte, []int) {
	return file_protocol_browser_v1_telemetry_proto_rawDescGZIP(), []int{5}
}

func (x *LoadAverage) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type Temperatures struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]float64     `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Temperatures) Reset() {
	*x = Temperatures{}
	mi := &file_protocol_browser_v1_telemetry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Temperatures) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Temperatures) ProtoMessage() {}

func (x *Temperatures) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_browser_v1_telemetry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Temperatures.ProtoReflect.Descriptor instead.
func (*Temperatures) Descriptor() ([]byte, []int) {
	return file_protocol_browser_v1_telemetry_proto_rawDescGZIP(), []int{6}
}

func (x *Temperatures) GetValues() map[string]float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type MissingMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]bool        `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MissingMetrics) Reset() {
	*x = MissingMetrics{}
	mi := &file_protocol_browser_v1_telemetry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissingMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissingMetrics) ProtoMessage() {}

func (x *MissingMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_browser_v1_telemetry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissingMetrics.ProtoReflect.Descriptor instead.
func (*MissingMetrics) Descriptor() ([]byte, []int) {
	return file_protocol_browser_v1_telemetry_proto_rawDescGZIP(), []int{7}
}

func (x *MissingMetrics) GetValues() map[string]bool {
	if x != nil {
		return x.Values
	}
	return nil
}

type Snapshot struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Timestamp        *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Available        *bool                  `protobuf:"varint,2,opt,name=available,proto3,oneof" json:"available,omitempty"`
	IsOnline         *bool                  `protobuf:"varint,3,opt,name=is_online,json=isOnline,proto3,oneof" json:"is_online,omitempty"`
	CpuUsagePercent  *FloatValue            `protobuf:"bytes,4,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	CpuIowaitPercent *FloatValue            `protobuf:"bytes,5,opt,name=cpu_iowait_percent,json=cpuIowaitPercent,proto3" json:"cpu_iowait_percent,omitempty"`
	CpuStealPercent  *FloatValue            `protobuf:"bytes,6,opt,name=cpu_steal_percent,json=cpuStealPercent,proto3" json:"cpu_steal_percent,omitempty"`
	RamUsedBytes     *UintValue             `protobuf:"bytes,7,opt,name=ram_used_bytes,json=ramUsedBytes,proto3" json:"ram_used_bytes,omitempty"`
	RamSwapUsedBytes *UintValue             `protobuf:"bytes,8,opt,name=ram_swap_used_bytes,json=ramSwapUsedBytes,proto3" json:"ram_swap_used_bytes,omitempty"`
	DiskUsedBytes    *UintValue             `protobuf:"bytes,9,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"`
	DiskTotalBytes   *UintValue             `protobuf:"bytes,10,opt,name=disk_total_bytes,json=diskTotalBytes,proto3" json:"disk_total_bytes,omitempty"`
	Disks            *DiskList              `protobuf:"bytes,11,opt,name=disks,proto3" json:"disks,omitempty"`
	LoadAvg          *LoadAverage           `protobuf:"bytes,12,opt,name=load_avg,json=loadAvg,proto3" json:"load_avg,omitempty"`
	Temperatures     *Temperatures          `protobuf:"bytes,13,opt,name=temperatures,proto3" json:"temperatures,omitempty"`
	RxBytes          *FloatValue            `protobuf:"bytes,14,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TxBytes          *FloatValue            `protobuf:"bytes,15,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	RxBps            *FloatValue            `protobuf:"bytes,16,opt,name=rx_bps,json=rxBps,proto3" json:"rx_bps,omitempty"`
	TxBps            *FloatValue            `protobuf:"bytes,17,opt,name=tx_bps,json=txBps,proto3" json:"tx_bps,omitempty"`
	DiskReadBps      *FloatValue            `protobuf:"bytes,18,opt,name=disk_read_bps,json=diskReadBps,proto3" json:"disk_read_bps,omitempty"`
	DiskWriteBps     *FloatValue            `protobuf:"bytes,19,opt,name=disk_write_bps,json=diskWriteBps,proto3" json:"disk_write_bps,omitempty"`
	Uptime           *uint32                `protobuf:"varint,20,opt,name=uptime,proto3,oneof" json:"uptime,omitempty"`
	Metadata         *Metadata              `protobuf:"bytes,21,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Missing          *MissingMetrics        `protobuf:"bytes,22,opt,name=missing,proto3" json:"missing,omitempty"`
	AgentId          *string                `protobuf:"bytes,23,opt,name=agent_id,json=agentId,proto3,oneof" json:"agent_id,omitempty"` // Authenticated owner snapshots only.
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_protocol_browser_v1_telemetry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_browser_v1_telemetry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_protocol_browser_v1_telemetry_proto_rawDescGZIP(), []int{8}
}

func (x *Snapshot) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Snapshot) GetAvailable() bool {
	if x != nil && x.Available != nil {
		return *x.Available
	}
	return false
}

func (x *Snapshot) GetIsOnline() bool {
	if x != nil && x.IsOnline != nil {
		return *x.IsOnline
	}
	return false
}

func (x *Snapshot) GetCpuUsagePercent() *FloatValue {
	if x != nil {
		return x.CpuUsagePercent
	}
	return nil
}

func (x *Snapshot) GetCpuIowaitPercent() *FloatValue {
	if x != nil {
		return x.CpuIowaitPercent
	}
	return nil
}

func (x *Snapshot) GetCpuStealPercent() *FloatValue {
	if x != nil {
		return x.CpuStealPercent
	}
	return nil
}

func (x *Snapshot) GetRamUsedBytes() *UintValue {
	if x != nil {
		return x.RamUsedBytes
	}
	return nil
}

func (x *Snapshot) GetRamSwapUsedBytes() *UintValue {
	if x != nil {
		return x.RamSwapUsedBytes
	}
	return nil
}

func (x *Snapshot) GetDiskUsedBytes() *UintValue {
	if x != nil {
		return x.DiskUsedBytes
	}
	return nil
}

func (x *Snapshot) GetDiskTotalBytes() *UintValue {
	if x != nil {
		return x.DiskTotalBytes
	}
	return nil
}

func (x *Snapshot) GetDisks() *DiskList {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *Snapshot) GetLoadAvg() *LoadAverage {
	if x != nil {
		return x.LoadAvg
	}
	return nil
}

func (x *Snapshot) GetTemperatures() *Temperatures {
	if x != nil {
		return x.Temperatures
	}
	return nil
}

func (x *Snapshot) GetRxBytes() *FloatValue {
	if x != nil {
		return x.RxBytes
	}
	return nil
}

func (x *Snapshot) GetTxBytes() *FloatValue {
	if x != nil {
		return x.TxBytes
	}
	return nil
}

func (x *Snapshot) GetRxBps() *FloatValue {
	if x != nil {
		return x.RxBps
	}
	return nil
}

func (x *Snapshot) GetTxBps() *FloatValue {
	if x != nil {
		return x.TxBps
	}
	return nil
}

func (x *Snapshot) GetDiskReadBps() *FloatValue {
	if x != nil {
		return x.DiskReadBps
	}
	return nil
}

func (x *Snapshot) GetDiskWriteBps() *FloatValue {
	if x != nil {
		return x.DiskWriteBps
	}
	return nil
}

func (x *Snapshot) GetUptime() uint32 {
	if x != nil && x.Uptime != nil {
		return *x.Uptime
	}
	return 0
}

func (x *Snapshot) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Snapshot) GetMissing() *MissingMetrics {
	if x != nil {
		return x.Missing
	}
	return nil
}

func (x *Snapshot) GetAgentId() string {
	if x != nil && x.AgentId != nil {
		return *x.AgentId
	}
	return ""
}

type Disk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	UsedBytes     *UintValue             `protobuf:"bytes,2,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	TotalBytes    *UintValue             `protobuf:"bytes,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	ReadBytes     *UintValue             `protobuf:"bytes,4,opt,name=read_bytes,json=readBytes,proto3" json:"read_bytes,omitempty"`
	WriteBytes    *UintValue             `protobuf:"bytes,5,opt,name=write_bytes,json=writeBytes,proto3" json:"write_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disk) Reset() {
	*x = Disk{}
	mi := &file_protocol_browser_v1_telemetry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disk) ProtoMessage() {}

func (x *Disk) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_browser_v1_telemetry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disk.ProtoReflect.Descriptor instead.
func (*Disk) Descriptor() ([]byte, []int) {
	return file_protocol_browser_v1_telemetry_proto_rawDescGZIP(), []int{9}
}

func (x *Disk) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Disk) GetUsedBytes() *UintValue {
	if x != nil {
		return x.UsedBytes
	}
	return nil
}

func (x *Disk) GetTotalBytes() *UintValue {
	if x != nil {
		return x.TotalBytes
	}
	return nil
}

func (x *Disk) GetReadBytes() *UintValue {
	if x != nil {
		return x.ReadBytes
	}
	return nil
}

func (x *Disk) GetWriteBytes() *UintValue {
	if x != nil {
		return x.WriteBytes
	}
	return nil
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uptime        uint32                 `protobuf:"varint,1,opt,name=uptime,proto3" json:"uptime,omitempty"`
	LinuxVersion  string                 `protobuf:"bytes,2,opt,name=linux_version,json=linuxVersion,proto3" json:"linux_version,omitempty"`
	CpuModel      string                 `protobuf:"bytes,3,opt,name=cpu_model,json=cpuModel,proto3" json:"cpu_model,omitempty"`
	CpuCores      uint32                 `protobuf:"varint,4,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	RamSize       uint64                 `protobuf:"varint,5,opt,name=ram_size,json=ramSize,proto3" json:"ram_size,omitempty"`
	SwapSize      uint64                 `protobuf:"varint,6,opt,name=swap_size,json=swapSize,proto3" json:"swap_size,omitempty"`
	DiskSize      uint64                 `protobuf:"varint,7,opt,name=disk_size,json=diskSize,proto3" json:"disk_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_protocol_browser_v1_telemetry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_browser_v1_telemetry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_protocol_browser_v1_telemetry_proto_rawDescGZIP(), []int{10}
}

func (x *Metadata) GetUptime() uint32 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *Metadata) GetLinuxVersion() string {
	if x != nil {
		return x.LinuxVersion
	}
	return ""
}

func (x *Metadata) GetCpuModel() string {
	if x != nil {
		return x.CpuModel
	}
	return ""
}

func (x *Metadata) GetCpuCores() uint32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *Metadata) GetRamSize() uint64 {
	if x != nil {
		return x.RamSize
	}
	return 0
}

func (x *Metadata) GetSwapSize() uint64 {
	if x != nil {
		return x.SwapSize
	}
	return 0
}

func (x *Metadata) GetDiskSize() uint64 {
	if x != nil {
		return x.DiskSize
	}
	return 0
}

var File_protocol_browser_v1_telemetry_proto protoreflect.FileDescriptor

const file_protocol_browser_v1_telemetry_proto_rawDesc = "" +
	"\n" +
	"#protocol/browser/v1/telemetry.proto\x12\x17certainstats.browser.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"R\n" +
	"\x11TelemetryEnvelope\x12=\n" +
	"\x05pulse\x18\x01 \x01(\v2'.certainstats.browser.v1.TelemetryPulseR\x05pulse\"\xbb\x01\n" +
	"\x0eTelemetryPulse\x12K\n" +
	"\x06agents\x18\x01 \x03(\v23.certainstats.browser.v1.TelemetryPulse.AgentsEntryR\x06agents\x1a\\\n" +
	"\vAgentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x127\n" +
	"\x05value\x18\x02 \x01(\v2!.certainstats.browser.v1.SnapshotR\x05value:\x028\x01\"1\n" +
	"\n" +
	"FloatValue\x12\x19\n" +
	"\x05value\x18\x01 \x01(\x01H\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"0\n" +
	"\tUintValue\x12\x19\n" +
	"\x05value\x18\x01 \x01(\x04H\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"?\n" +
	"\bDiskList\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.certainstats.browser.v1.DiskR\x05items\"%\n" +
	"\vLoadAverage\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x01R\x06values\"\x94\x01\n" +
	"\fTemperatures\x12I\n" +
	"\x06values\x18\x01 \x03(\v21.certainstats.browser.v1.Temperatures.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\x98\x01\n" +
	"\x0eMissingMetrics\x12K\n" +
	"\x06values\x18\x01 \x03(\v23.certainstats.browser.v1.MissingMetrics.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\xf9\v\n" +
	"\bSnapshot\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12!\n" +
	"\tavailable\x18\x02 \x01(\bH\x00R\tavailable\x88\x01\x01\x12 \n" +
	"\tis_online\x18\x03 \x01(\bH\x01R\bisOnline\x88\x01\x01\x12O\n" +
	"\x11cpu_usage_percent\x18\x04 \x01(\v2#.certainstats.browser.v1.FloatValueR\x0fcpuUsagePercent\x12Q\n" +
	"\x12cpu_iowait_percent\x18\x05 \x01(\v2#.certainstats.browser.v1.FloatValueR\x10cpuIowaitPercent\x12O\n" +
	"\x11cpu_steal_percent\x18\x06 \x01(\v2#.certainstats.browser.v1.FloatValueR\x0fcpuStealPercent\x12H\n" +
	"\x0eram_used_bytes\x18\a \x01(\v2\".certainstats.browser.v1.UintValueR\framUsedBytes\x12Q\n" +
	"\x13ram_swap_used_bytes\x18\b \x01(\v2\".certainstats.browser.v1.UintValueR\x10ramSwapUsedBytes\x12J\n" +
	"\x0fdisk_used_bytes\x18\t \x01(\v2\".certainstats.browser.v1.UintValueR\rdiskUsedBytes\x12L\n" +
	"\x10disk_total_bytes\x18\n" +
	" \x01(\v2\".certainstats.browser.v1.UintValueR\x0ediskTotalBytes\x127\n" +
	"\x05disks\x18\v \x01(\v2!.certainstats.browser.v1.DiskListR\x05disks\x12?\n" +
	"\bload_avg\x18\f \x01(\v2$.certainstats.browser.v1.LoadAverageR\aloadAvg\x12I\n" +
	"\ftemperatures\x18\r \x01(\v2%.certainstats.browser.v1.TemperaturesR\ftemperatures\x12>\n" +
	"\brx_bytes\x18\x0e \x01(\v2#.certainstats.browser.v1.FloatValueR\arxBytes\x12>\n" +
	"\btx_bytes\x18\x0f \x01(\v2#.certainstats.browser.v1.FloatValueR\atxBytes\x12:\n" +
	"\x06rx_bps\x18\x10 \x01(\v2#.certainstats.browser.v1.FloatValueR\x05rxBps\x12:\n" +
	"\x06tx_bps\x18\x11 \x01(\v2#.certainstats.browser.v1.FloatValueR\x05txBps\x12G\n" +
	"\rdisk_read_bps\x18\x12 \x01(\v2#.certainstats.browser.v1.FloatValueR\vdiskReadBps\x12I\n" +
	"\x0edisk_write_bps\x18\x13 \x01(\v2#.certainstats.browser.v1.FloatValueR\fdiskWriteBps\x12\x1b\n" +
	"\x06uptime\x18\x14 \x01(\rH\x02R\x06uptime\x88\x01\x01\x12=\n" +
	"\bmetadata\x18\x15 \x01(\v2!.certainstats.browser.v1.MetadataR\bmetadata\x12A\n" +
	"\amissing\x18\x16 \x01(\v2'.certainstats.browser.v1.MissingMetricsR\amissing\x12\x1e\n" +
	"\bagent_id\x18\x17 \x01(\tH\x03R\aagentId\x88\x01\x01B\f\n" +
	"\n" +
	"_availableB\f\n" +
	"\n" +
	"_is_onlineB\t\n" +
	"\a_uptimeB\v\n" +
	"\t_agent_id\"\xaa\x02\n" +
	"\x04Disk\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12A\n" +
	"\n" +
	"used_bytes\x18\x02 \x01(\v2\".certainstats.browser.v1.UintValueR\tusedBytes\x12C\n" +
	"\vtotal_bytes\x18\x03 \x01(\v2\".certainstats.browser.v1.UintValueR\n" +
	"totalBytes\x12A\n" +
	"\n" +
	"read_bytes\x18\x04 \x01(\v2\".certainstats.browser.v1.UintValueR\treadBytes\x12C\n" +
	"\vwrite_bytes\x18\x05 \x01(\v2\".certainstats.browser.v1.UintValueR\n" +
	"writeBytes\"\xd6\x01\n" +
	"\bMetadata\x12\x16\n" +
	"\x06uptime\x18\x01 \x01(\rR\x06uptime\x12#\n" +
	"\rlinux_version\x18\x02 \x01(\tR\flinuxVersion\x12\x1b\n" +
	"\tcpu_model\x18\x03 \x01(\tR\bcpuModel\x12\x1b\n" +
	"\tcpu_cores\x18\x04 \x01(\rR\bcpuCores\x12\x19\n" +
	"\bram_size\x18\x05 \x01(\x04R\aramSize\x12\x1b\n" +
	"\tswap_size\x18\x06 \x01(\x04R\bswapSize\x12\x1b\n" +
	"\tdisk_size\x18\a \x01(\x04R\bdiskSizeB$Z\"certainstats/internal/ws/browserpbb\x06proto3"

var (
	file_protocol_browser_v1_telemetry_proto_rawDescOnce sync.Once
	file_protocol_browser_v1_telemetry_proto_rawDescData []byte
)

func file_protocol_browser_v1_telemetry_proto_rawDescGZIP() []byte {
	file_protocol_browser_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_protocol_browser_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_browser_v1_telemetry_proto_rawDesc), len(file_protocol_browser_v1_telemetry_proto_rawDesc)))
	})
	return file_protocol_browser_v1_telemetry_proto_rawDescData
}

var file_protocol_browser_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_protocol_browser_v1_telemetry_proto_goTypes = []any{
	(*TelemetryEnvelope)(nil),     // 0: certainstats.browser.v1.TelemetryEnvelope
	(*TelemetryPulse)(nil),        // 1: certainstats.browser.v1.TelemetryPulse
	(*FloatValue)(nil),            // 2: certainstats.browser.v1.FloatValue
	(*UintValue)(nil),             // 3: certainstats.browser.v1.UintValue
	(*DiskList)(nil),              // 4: certainstats.browser.v1.DiskList
	(*LoadAverage)(nil),           // 5: certainstats.browser.v1.LoadAverage
	(*Temperatures)(nil),          // 6: certainstats.browser.v1.Temperatures
	(*MissingMetrics)(nil),        // 7: certainstats.browser.v1.MissingMetrics
	(*Snapshot)(nil),              // 8: certainstats.browser.v1.Snapshot
	(*Disk)(nil),                  // 9: certainstats.browser.v1.Disk
	(*Metadata)(nil),              // 10: certainstats.browser.v1.Metadata
	nil,                           // 11: certainstats.browser.v1.TelemetryPulse.AgentsEntry
	nil,                           // 12: certainstats.browser.v1.Temperatures.ValuesEntry
	nil,                           // 13: certainstats.browser.v1.MissingMetrics.ValuesEntry
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_protocol_browser_v1_telemetry_proto_depIdxs = []int32{
	1,  // 0: certainstats.browser.v1.TelemetryEnvelope.pulse:type_name -> certainstats.browser.v1.TelemetryPulse
	11, // 1: certainstats.browser.v1.TelemetryPulse.agents:type_name -> certainstats.browser.v1.TelemetryPulse.AgentsEntry
	9,  // 2: certainstats.browser.v1.DiskList.items:type_name -> certainstats.browser.v1.Disk
	12, // 3: certainstats.browser.v1.Temperatures.values:type_name -> certainstats.browser.v1.Temperatures.ValuesEntry
	13, // 4: certainstats.browser.v1.MissingMetrics.values:type_name -> certainstats.browser.v1.MissingMetrics.ValuesEntry
	14, // 5: certainstats.browser.v1.Snapshot.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 6: certainstats.browser.v1.Snapshot.cpu_usage_percent:type_name -> certainstats.browser.v1.FloatValue
	2,  // 7: certainstats.browser.v1.Snapshot.cpu_iowait_percent:type_name -> certainstats.browser.v1.FloatValue
	2,  // 8: certainstats.browser.v1.Snapshot.cpu_steal_percent:type_name -> certainstats.browser.v1.FloatValue
	3,  // 9: certainstats.browser.v1.Snapshot.ram_used_bytes:type_name -> certainstats.browser.v1.UintValue
	3,  // 10: certainstats.browser.v1.Snapshot.ram_swap_used_bytes:type_name -> certainstats.browser.v1.UintValue
	3,  // 11: certainstats.browser.v1.Snapshot.disk_used_bytes:type_name -> certainstats.browser.v1.UintValue
	3,  // 12: certainstats.browser.v1.Snapshot.disk_total_bytes:type_name -> certainstats.browser.v1.UintValue
	4,  // 13: certainstats.browser.v1.Snapshot.disks:type_name -> certainstats.browser.v1.DiskList
	5,  // 14: certainstats.browser.v1.Snapshot.load_avg:type_name -> certainstats.browser.v1.LoadAverage
	6,  // 15: certainstats.browser.v1.Snapshot.temperatures:type_name -> certainstats.browser.v1.Temperatures
	2,  // 16: certainstats.browser.v1.Snapshot.rx_bytes:type_name -> certainstats.browser.v1.FloatValue
	2,  // 17: certainstats.browser.v1.Snapshot.tx_bytes:type_name -> certainstats.browser.v1.FloatValue
	2,  // 18: certainstats.browser.v1.Snapshot.rx_bps:type_name -> certainstats.browser.v1.FloatValue
	2,  // 19: certainstats.browser.v1.Snapshot.tx_bps:type_name -> certainstats.browser.v1.FloatValue
	2,  // 20: certainstats.browser.v1.Snapshot.disk_read_bps:type_name -> certainstats.browser.v1.FloatValue
	2,  // 21: certainstats.browser.v1.Snapshot.disk_write_bps:type_name -> certainstats.browser.v1.FloatValue
	10, // 22: certainstats.browser.v1.Snapshot.metadata:type_name -> certainstats.browser.v1.Metadata
	7,  // 23: certainstats.browser.v1.Snapshot.missing:type_name -> certainstats.browser.v1.MissingMetrics
	3,  // 24: certainstats.browser.v1.Disk.used_bytes:type_name -> certainstats.browser.v1.UintValue
	3,  // 25: certainstats.browser.v1.Disk.total_bytes:type_name -> certainstats.browser.v1.UintValue
	3,  // 26: certainstats.browser.v1.Disk.read_bytes:type_name -> certainstats.browser.v1.UintValue
	3,  // 27: certainstats.browser.v1.Disk.write_bytes:type_name -> certainstats.browser.v1.UintValue
	8,  // 28: certainstats.browser.v1.TelemetryPulse.AgentsEntry.value:type_name -> certainstats.browser.v1.Snapshot
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_protocol_browser_v1_telemetry_proto_init() }
func file_protocol_browser_v1_telemetry_proto_init() {
	if File_protocol_browser_v1_telemetry_proto != nil {
		return
	}
	file_protocol_browser_v1_telemetry_proto_msgTypes[2].OneofWrappers = []any{}
	file_protocol_browser_v1_telemetry_proto_msgTypes[3].OneofWrappers = []any{}
	file_protocol_browser_v1_telemetry_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_browser_v1_telemetry_proto_rawDesc), len(file_protocol_browser_v1_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_browser_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_protocol_browser_v1_telemetry_proto_depIdxs,
		MessageInfos:      file_protocol_browser_v1_telemetry_proto_msgTypes,
	}.Build()
	File_protocol_browser_v1_telemetry_proto = out.File
	file_protocol_browser_v1_telemetry_proto_goTypes = nil
	file_protocol_browser_v1_telemetry_proto_depIdxs = nil
}
